before_install:
    - sudo apt-get update
    - sudo apt-get install -qq doxygen
    - gem install sass --version "=3.2.12"
    - gem install compass --version "=0.12.2"

language: node_js
node_js: "0.10"
env:
    global:
        - secure: "NMv9a+t30l1Cf+MgO6OHpcKaK+yraCD6imDLwjt15Z9SIkKk5S70q2xt16ccRDDrn7x78C771WRkgN1ZgLW7T1gEOGB0bNt7gk2bSS+NoCbgL+/T4lWV3a/4+X+Ol6F8l6EuzlMX84FtGcegxMYWQd16pBvpAXeCkHmImOV5264="

script:
    - git config --global user.name "Travis-CI"
    - git config --global user.email ${GIT_EMAIL}
    - git clone --quiet https://github.com/HalfdanJ/openFrameworks.git
    - cd openFrameworks; git checkout documentation; cd ..; 
    - cd openFrameworks/libs/openFrameworksCompiled/project/doxygen/; doxygen Doxyfile; cd ../../../../../
    - node app openFrameworks
    - npm run sass;
    - mkdir ghpages
    - cd ghpages
    - git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/HalfdanJ/ofDocGenerator.git . > /dev/null
    - cp -R ../output/* .
    - git add --all .
    - git commit -m "Auto update ofDoc from Travis-ci"
    - git remote set-url origin "https://${GH_TOKEN}@github.com/HalfdanJ/ofDocGenerator.git"
    - git push -fq origin gh-pages
